### ISSUE TITLE
No build provided for release 1.1.0?

### ISSUE THREAD

**Issue by Ellypse** [tangzx/IntelliJ-EmmyLua#10]
Hi.

Sorry to bother you, but I have noticed that for the releases 1.0.7 and 1.1.0 you are no longer providing a .zip file with the build of the plugin (the .jar file), only the source code. I don't know how to build a plugin for IntelliJ from the source code and the builds you made with the previous releases were really helpful.
Would you consider providing a build for the latest release, please? :)

Thanks again for this great plugin and for working so hard on it. I love it so much.

**Comment by tangzx** [comment]
that's my mistake. but i found a SSSSSS level bug, so i cancelled this release. it will comes soon.

**Comment by Ellypse** [comment]
Hi again. Thanks for your reply and for the new build :)

**Comment by tangzx** [comment]
U are welcome. and also welcome your suggestions, bugs feed back ...
