### ISSUE TITLE
Suggestion: Some sort of class inheritance tag?

### ISSUE THREAD

**Issue by Ellypse** [tangzx/IntelliJ-EmmyLua#11]
Hi again. I just saw your comment asking for suggestions and I may have really specific one.

I'm using your Lua plugin to develop World of Warcraft add-ons. World of Warcraft's API provides widgets that you can use for your UI and that have methods provided with them. I have exported the widgets' API from a website so that the plugin can use it to provide method completions (I have a separate repo for the exported API here https://github.com/Ellypse/IntelliJ-IDEA-Lua-IDE-WoW-API/tree/master/widgets).

The API files declare a class for each widget with their specific methods like this:
```lua
---@class Button
Button = {};
function Button:SetText(text) end

---@class UIObject
UIObject = {};
function UIObject:GetName() end
```

I can then document my code and get code completion for the methods of a widget like this:
```lua
---@type Button
local myButton = CreateFrame("Button");
myButton:SetText("foo"); -- code completion provided by the Button.lua API file
```

But the widgets are actually part of a hierarchical tree and inherits their parents methods. A graphical representation of the tree is available here http://wowprogramming.com/docs/widgets_hierarchy . So for example a Button inherits the methods of the Frame, VisibleRegion, Region, ScriptObject, ParentedObject and UIObject.

If in my code I do the follow code I can get code completion from all these widgets
```lua
---@type Button, Frame, VisibleRegion, Region, ScriptObject, ParentedObject, UIObject
local myButton = CreateFrame("Button");
myButton:SetText("foo"); -- code completion provided by the Button.lua API file
local name = myButton:GetName(); -- code completion provided by the UIObject.lua API file
```

What I would like to suggest, if that's possible, is a way to indicate that a class inherits method from another class for code completion, so that I only have to indicate the parents widgets in the Button API instead of everywhere I use a Button, something like
```lua
---@class Button
---@inherits Frame, VisibleRegion, Region, ScriptObject, ParentedObject, UIObject
Button = {};
function Button:SetText(text) end

---@type Button
local myButton = CreateFrame("Button");
myButton:SetText("foo"); -- code completion provided by the Button.lua API file
local name = myButton:GetName(); -- code completion provided by the UIObject.lua API file
```

I have tried to add a `---@type` tag for the Button before and after the `---@class` tag but they do not seem to play well together.

I don't know if that's possible and how easy it would be for you. I have been thinking about modifying my script to export the widgets API to insert all the inherited methods inside each children, but I like how it present the methods with the class it comes from when it actually pulls them from all the different classes.

<img width="653" alt="capture d ecran 2017-05-05 a 09 32 54" src="https://cloud.githubusercontent.com/assets/9035119/25737040/ded27dd2-3175-11e7-82e7-47509660f6bb.png">

**Comment by tangzx** [comment]
HI @Ellypse
The full useage of `---@class` tag/annotation  is : `---@class YOUR_CLASS : PARENT_CLASS @Comment`
In your case, just do this `---@class Button : UIObject` and `---@class UIObject : UIFrame` ...
But multi-inherits is not support, I think that's bad design, may be interface is a perfect choice.

Any way, thanks for your suggestion, I will consider it

**Comment by Ellypse** [comment]
Oh, thanks! I have annotated my classes like you said (with only one parent for now, the one I think is the most important parent) and I can confirm that it works, I see the methods from all the parents in the chain.

As for multiple "parents", I completely agree with you that the word inherits is a bad choice and interfaces are a better choices :)
