### ISSUE TITLE
--[[ ]]-- block comments do not work at all

### ISSUE THREAD

**Issue by DoctorGester** [tangzx/IntelliJ-EmmyLua#19]
![image](https://cloud.githubusercontent.com/assets/3684394/26543453/b0ba9f34-4466-11e7-8109-f6d0a0d9c8c3.png)

**Comment by DoctorGester** [comment]
Seems like a bug actually, after deleting any line the comment is highlighted properly

**Comment by tangzx** [comment]
yes, it's a bug, highlighting does not refresh immediately. it was been fixed, please wait for next release
