### ISSUE TITLE
function end autocompletion breaks code indentation if attempted to be used while inside a table

### ISSUE THREAD

**Issue by DoctorGester** [tangzx/IntelliJ-EmmyLua#20]
```lua
function c()
    local a = {
        b = function()
    }

    someTestMemes()
end
```

My cursor is after function(), when I press enter it turns into

```
function c()
    local a = {
        b = function()
            }
            }

            someTestMemes()
        end
```

**Comment by DoctorGester** [comment]
I also found that this applies to many other cases but I didn't record them. In general autocompletion in syntactically incorrect code often produces weird results.

**Comment by DoctorGester** [comment]
This is still present and is horribly annoying

Try

```lua
function dog()
	bob({
		gog = function()
			if bork then
		end
	})
end
```

Put your cursor after 'then' and press enter, code ruined

**Comment by tangzx** [comment]
fixed!
![bug 20](https://user-images.githubusercontent.com/3354360/28602883-3232de32-71f3-11e7-94cc-d80df9a6046c.gif)

**Comment by tangzx** [comment]
![bug 20 2](https://user-images.githubusercontent.com/3354360/28603018-1e8a80a0-71f4-11e7-98ae-6685d48e33b0.gif)

**Comment by DoctorGester** [comment]
Nice! Thank you
