### ISSUE TITLE
类的成员变量，已经被标记的，无法ctrl+o 列出来，只列出了函数

### ISSUE THREAD

**Issue by 49694445** [tangzx/IntelliJ-EmmyLua#25]
另外一个问题，子类继承父类以后。 父类的成员变量，在子类里可以自动补全，但是点过去的位置不是定位在父类那里，而是在别处

**Comment by 49694445** [comment]
子类继承父类以后。 父类的成员变量，在子类里可以自动补全，但是点过去的位置不是定位在父类那里，而是在别处

这个问题有的有，有的没有

**Comment by tangzx** [comment]
解决

**Comment by 49694445** [comment]
没有解决啊。一样的。类的成员变量，已经被标记的，无法ctrl+o 列出来

**Comment by 49694445** [comment]
我是1.1.5的

**Comment by 49694445** [comment]
子类使用父类属性，
print(self.range)  这里点父类这个属性，不是跳转父类定义变量处，而是父类写变量的地方。
    self.range=3  这里点属性就没任何反应了。
