### ISSUE TITLE
Hashbang support (#!)

### ISSUE THREAD

**Issue by mqualizz** [tangzx/IntelliJ-EmmyLua#31]
Excellent job on this plugin!

There is one feature that I hope you can add -- hashbang* support.  The lack of hashbang support is the only thing that prevents me from using EmmyLua.

\* hashbang, if you are not familiar with it, is a unix-style way of declaring which executable to use to run a script.  For more information https://en.wikipedia.org/wiki/Shebang_(Unix)

**Comment by tangzx** [comment]
OK, see next version
