### ISSUE TITLE
enter自动插入end后会自动缩进当前位置直到到文档末尾

### ISSUE THREAD

**Issue by LiamYao** [tangzx/IntelliJ-EmmyLua#32]
有时并不希望格式化整个文档
应该是LuaEnterAfterUnmatchedBraceHandler里的styleManager.adjustLineIndent(psiFile, textRange)做了这个操作，这里的textRange大部分情况下是到整个文档末尾的

**Comment by tangzx** [comment]
你用的是什么版本？这个问题好像已经解决了，或者等下个版本

**Comment by tangzx** [comment]
#20 已修复

**Comment by tangzx** [comment]
@Duplicate of #20

**Comment by LiamYao** [comment]
master最新版本编译试了下，应该还是有这个问题， if true then 后面enter后，test2这一行的缩进会被干掉
```
test1=1
function a()
    if true then
end

    test2 = 2
```

**Comment by tangzx** [comment]
:+1: 试了一下的确存在，试试最新的提交

**Comment by LiamYao** [comment]
可以了！
