### ISSUE TITLE
发现的几个问题

### ISSUE THREAD

**Issue by yuz10** [tangzx/IntelliJ-EmmyLua#36]
1 输入数字后回车，会自动输入第一个提示项
2 无法导航到require引用的文件

**Comment by tangzx** [comment]
1. 已解决 [9a97856](https://github.com/tangzx/IntelliJ-EmmyLua/commit/9a97856fd9a5ddbb49227544fcf1beb3a92bea24)，等下个版本
2. 检查一下sources root设置

**Comment by yuz10** [comment]
太给力了
