### ISSUE TITLE
Lua breakpoints on Javascript Code

### ISSUE THREAD

**Issue by rvalle** [tangzx/IntelliJ-EmmyLua#38]
I have added this plugin to Webstorm to highlight the syntax of a couple of lua files to be used with redis.

My project is mainly javascript/nodejs files.
After installing this plugin, breakpoints on javascript don't work anymore.

Looking into the breakpoint information, breakpoints on JavaScript files seem to be handled by lua-line-breakpoint instead of JavaScript line breakpoints.

lua-line-breakpoints should handle only breakpoints on lua files and not javascript files, I guess.

I could not find any way to configure/modify this behaviour, so I had to disable this Lua plugin.

**Comment by tangzx** [comment]
thanks for your feedback, I'll check it.
