### ISSUE TITLE
handler.lua无法识别

### ISSUE THREAD

**Issue by yuz10** [tangzx/IntelliJ-EmmyLua#40]
更新后， handler.lua无法识别为lua文件

**Comment by tangzx** [comment]
问题描述的不够详细，是只有这个文件无法识别？还是所有的，如果只是这个文件无法识别有可能是你在此文件上点击了右键->`Mark as Plain Text`，恢复lua识别同样右键->`Mark as Lua`。如果是全部文件不能被识别则有可能是`EmmyLua`插件没安装成功，在插件管理面板里看看`EmmyLua`插件安装和激活情况

**Comment by yuz10** [comment]
所有handler.lua都无法识别，新建一个项目，然后新建和一个handler.lua即可复现。idea community版本。

**Comment by tangzx** [comment]
其它文件都OK？那应该是你哪里做了什么设置忽略了文件之类的？自己查查看
