### ISSUE TITLE
Problems with "smart enter"

### ISSUE THREAD

**Issue by mqualizz** [tangzx/IntelliJ-EmmyLua#41]
I love your plugin -- it gets better with every release.

I have found a few issues with the "smart enter" completion behaviour.

As far as I can tell, if you hit &lt;enter> two things happen w.r.t completion behaviour/"smart enter":
1. If the cursor is in a block with a missing `end` then an `end` is inserted on the next line (same with`until`, etc)
2. Some code is reformatted

First, please, please, please remove (2), or add an option to turn off automatic code formatting.  Not only do I hate it when my code is reformatted by the IDE, but the current logic has some bugs which makes the reformatting 'broken' in certain situations.

Bugs:
1. In the simple case, the cursor is not properly positioned.
E.g. (for this, and all further examples, | represents the position of the cursor)
If you have
```
if someCondition then|
```
and hit &lt;enter>, you get
```
if someCondition then|
end
```
instead of
```
if someCondition then
    |
end
```

2. If there is no space between the current keyword and the missing `end` (etc) from an outer block, the `end` is not recognized.  And things get weird.

e.g. Just say this is your original code
```
if a then doSomething() end
nextLine
anotherLine
thirdline
```

then you replace `doSomething()` with another (incomplete) condition, (notice, no space between `then` and `end`)
```
if a then if b then|end
nextLine
anotherLine
thirdline
```

and hit &lt;enter> (notice how then `end` keyword is inserted, but incorrectly, how the `end` following the cursor is not recognized, and how everything gets indented when it shouldn't be)
```
if a then if b then|
    endend
    nextLine
    anotherLine
    thirdline
```
and hit &lt;enter> a second time (this is just the first bug showing up again)
```
if a then if b then
end
    endend
    nextLine
    anotherLine
    thirdline
```
The behaviour seems to depend on what follows the cursor.  For example:
Initial code:
```
if a then return end
nextLine
anotherLine
thirdline
```
Add a new, incomplete condition (again, no space between `then` and `return`)
```
if a then if b then|return end
nextLine
anotherLine
thirdline
```
hit &lt;enter>
```
if a then if b then|
    endreturn end
nextLine
anotherLine
thirdline
```
hit &lt;enter> again
```
if a then if b then|
end
    endreturn end
nextLine
anotherLine
thirdline
```

**Comment by DoctorGester** [comment]
Oh so that's when reformat happens... I couldn't quite catch it, very annoying indeed

**Comment by tangzx** [comment]
Thanks a good issue. 
![image](https://user-images.githubusercontent.com/3354360/29851512-02615816-8d67-11e7-81e7-ccc96ee909a1.png)
![image](https://user-images.githubusercontent.com/3354360/29851521-0b1c8142-8d67-11e7-840c-333b3204f966.png)

Also added a settings for smart enter, you can on/off it :smiley: 
![image](https://user-images.githubusercontent.com/3354360/29851563-4c1dc8c2-8d67-11e7-8637-6d55b3299053.png)

Anything else?

**Comment by mqualizz** [comment]
You're awesome, thank you :-)

Does that "smart close 'end'" feature also cover "until"?  For example, `repeat if a then|until condition`.
