### ISSUE TITLE
Ctrl-P (Parameter info) does not work reliably

### ISSUE THREAD

**Issue by Jendrik3** [tangzx/IntelliJ-EmmyLua#47]
Are there any plans to support Ctrl-P?

EDIT:

It looks like it works for `string.find`, `string.len` and `pcall` but not for `string.lower`.

**Comment by tangzx** [comment]
already supported
![2017-09-07_11-51-49](https://user-images.githubusercontent.com/3354360/30145285-044aa8be-93c3-11e7-9490-727c70448192.gif)

**Comment by Jendrik3** [comment]
That's strange. I works for me now. I don't know what I did on my side. You can close this issue.

**Comment by tangzx** [comment]
:ok_hand:
