### ISSUE TITLE
2017.3 EAP Compatibility

### ISSUE THREAD

**Issue by mqualizz** [tangzx/IntelliJ-EmmyLua#48]
I'm not sure what IntelliJ maturity level you are interested in tracking, but EmmyLua 1.1.8 is marked as "not compatible" with 2017.3 (173.2099.14)

**Comment by tangzx** [comment]
I will release new version to compatible with 173

**Comment by krstns** [comment]
When can we expect this?

**Comment by tangzx** [comment]
@krstns in this week, as quick as possible
