### ISSUE TITLE
List of typed functions

### ISSUE THREAD

**Issue by Perryvw** [tangzx/IntelliJ-EmmyLua#55]
I would like to define a list of functions of a certain type. I would expect this to work as follows:
```
--- @type (fun(a: b): c)[]
local funcList = {}
```
This throws an error `<type set> expected, got '(' ` 

Note that `--- @type fun(a: b): c[]` is allowed, but this defines a singular function that returns a list of c, instead of a list of functions that each return a singular c.

A slightly looser definition with a table does work:
```
--- @type table<number, fun(a: b): c>
local funcList = {}
```

**Comment by tangzx** [comment]
OK, now spports wrap type with parentheses
![image](https://user-images.githubusercontent.com/3354360/30789389-d99ca18a-a1d7-11e7-8454-53099371660b.png)
