### ISSUE TITLE
Default highlight for nil/true/false is not bright colour scheme friendly 

### ISSUE THREAD

**Issue by narqo** [tangzx/IntelliJ-EmmyLua#57]
By default, the plugin uses Bright Cyan to highlight nil/true/false identifiers. This might work for dark colour schemes, e.g. Darcula, but it doesn't for bright one. While it's not a hard job to tune the colours, I strongly believe that it's worth having good defaults.

I propose to use Identifiers → Constant (Language Defaults) colour, the same one that is used in some other languages.

**Comment by tangzx** [comment]
fixed!
![image](https://user-images.githubusercontent.com/3354360/31490221-c8349e42-af75-11e7-8df8-b12a938a454d.png)
