### ISSUE TITLE
添加type function

### ISSUE THREAD

**Issue by jinsediaoying** [tangzx/IntelliJ-EmmyLua#6]
添加把变量类型标记为function的功能
简易版
---@type function
---@param xxxxx xxxxx
...
boo.func

完美版
---#type function(A, [B], A|B, params C):E, F|G

[B]--可选参数
A|B--多类型参数
params C--可变数量参数
：--冒号后面是返回类型，支持多个返回值

完美版可以替换现有的param，return标记，一行搞定，简洁得多，让param和return只在需要注释的时候使用

**Comment by tangzx** [comment]
可能是这种形式
---#type function(a:A, b:[B], c:A|B, ...):E, F|G

**Comment by QingMings** [comment]
idea 插件仓库没有么？

**Comment by tangzx** [comment]
@QingMings 暂时没有，等正式完成时再上架仓库吧，现在还有一些问题没解决

**Comment by QingMings** [comment]
好的

**Comment by tangzx** [comment]
已支持
